export const SET_ACTIVE_MEAL = 'SET_ACTIVE_MEAL';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_SEARCH = 'SET_SEARCH';
export const FETCH_FOODS_START = 'FETCH_FOODS_START';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAILURE = 'FETCH_FOODS_FAILURE';
export const SET_SELECTED_FOOD = 'SET_SELECTED_FOOD'