/**
 * Tác dụng của file: Khai báo toàn bộ các hằng số ACTIONS phục vụ quản lý sự kiện trạng thái của Nhật ký & Thực đơn.
 */
export const ACTIONS = {
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  FETCH_DAILY_LOG_START: 'FETCH_DAILY_LOG_START',
  FETCH_DAILY_LOG_SUCCESS: 'FETCH_DAILY_LOG_SUCCESS',
  FETCH_USER_GOAL_SUCCESS: 'FETCH_USER_GOAL_SUCCESS',
  FETCH_FAVORITES_SUCCESS: 'FETCH_FAVORITES_SUCCESS',
  UPDATE_DIET_PRESET: 'UPDATE_DIET_PRESET',
  UPDATE_WATER_SUCCESS: 'UPDATE_WATER_SUCCESS',
};

