export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const FETCH_DAILY_LOG_START = 'FETCH_DAILY_LOG_START';
export const FETCH_DAILY_LOG_SUCCESS = 'FETCH_DAILY_LOG_SUCCESS';
export const FETCH_USER_GOAL_SUCCESS = 'FETCH_USER_GOAL_SUCCESS';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const UPDATE_DIET_PRESET = 'UPDATE_DIET_PRESET';
export const UPDATE_WATER_SUCCESS = 'UPDATE_WATER_SUCCESS';
export const SET_ACTIVE_MEAL = 'SET_ACTIVE_MEAL';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_SEARCH = 'SET_SEARCH';
export const FETCH_FOODS_START = 'FETCH_FOODS_START';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAILURE = 'FETCH_FOODS_FAILURE';
export const SET_SELECTED_FOOD = 'SET_SELECTED_FOOD';

// WORKOUT
export const SET_WORKOUT_VIEW = 'SET_WORKOUT_VIEW';
export const SET_WORKOUT_ACTIVE_TAB = 'SET_WORKOUT_ACTIVE_TAB';
export const SET_WORKOUT_SEARCH = 'SET_WORKOUT_SEARCH';
export const SET_WORKOUT_SHOW_FILTERS = 'SET_WORKOUT_SHOW_FILTERS';
export const SET_WORKOUT_SELECTED_MUSCLES = 'SET_WORKOUT_SELECTED_MUSCLES';
export const SET_WORKOUT_RATING_FILTER = 'SET_WORKOUT_RATING_FILTER';
export const SET_WORKOUT_IS_CUSTOM = 'SET_WORKOUT_IS_CUSTOM';
export const SET_WORKOUT_IS_FAVORITE = 'SET_WORKOUT_IS_FAVORITE';

export const FETCH_EXERCISES_START = 'FETCH_EXERCISES_START';
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS';
export const FETCH_EXERCISES_FAILURE = 'FETCH_EXERCISES_FAILURE';

export const SET_WORKOUT_SELECTED_EXERCISE = 'SET_WORKOUT_SELECTED_EXERCISE';
export const SET_WORKOUT_EXERCISE_MODE = 'SET_WORKOUT_EXERCISE_MODE';
export const SET_WORKOUT_SETS = 'SET_WORKOUT_SETS';
export const SET_WORKOUT_REPS_OR_TIME = 'SET_WORKOUT_REPS_OR_TIME';
export const SET_WORKOUT_REST_TIME = 'SET_WORKOUT_REST_TIME';
export const SET_WORKOUT_SELECTED_DATE = 'SET_WORKOUT_SELECTED_DATE';
export const SET_WORKOUT_SELECTED_TIME = 'SET_WORKOUT_SELECTED_TIME';

export const SET_SCHEDULED_EXERCISES = 'SET_SCHEDULED_EXERCISES';
export const SET_CURRENT_EXERCISE_INDEX = 'SET_CURRENT_EXERCISE_INDEX';

export const FETCH_EXERCISE_HISTORY_START = 'FETCH_EXERCISE_HISTORY_START';
export const FETCH_EXERCISE_HISTORY_SUCCESS = 'FETCH_EXERCISE_HISTORY_SUCCESS';
export const FETCH_EXERCISE_HISTORY_FAILURE = 'FETCH_EXERCISE_HISTORY_FAILURE';
